# Generated by Django 2.2.24 on 2023-04-18 13:01

from django.db import migrations


def define_field_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    year_marker = 2015
    Flat.objects.filter(
        construction_year__gte=year_marker
    ).update(new_building=True)
    Flat.objects.filter(
        construction_year__lt=year_marker
    ).update(new_building=False)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(define_field_new_building),
    ]
